export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'
export const GET_ERROR = 'GET_ERROR'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
